AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  HostedZoneName:
    Type: String
    Default: dev-resas.com
  OriginHostName:
    Type: String
    Default: it.dev-resas.com
  RedirectHostName:
    Type: String
    Default: stage.dev-resas.com

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OriginHostName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RedirectHostName
          Protocol: https

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref OriginHostName
      ValidationMethod: DNS

  CloudFrontDistributon:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub "${OriginHostName}.s3-website-${AWS::Region}.amazonaws.com"
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
          Id: !Sub "S3-Website-${OriginHostName}.s3-website-${AWS::Region}.amazonaws.com"
        Enabled: true
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: !Sub "S3-Website-${OriginHostName}.s3-website-${AWS::Region}.amazonaws.com"
          ViewerProtocolPolicy: allow-all
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        HttpVersion: http2
        Aliases:
        - !Ref OriginHostName

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${HostedZoneName}."
      Name: !Sub "${OriginHostName}."
      Type: CNAME
      TTL: 300
      ResourceRecords:
      - !GetAtt CloudFrontDistributon.DomainName

Outputs:
  HttpURI:
    Value: !Sub "http://${OriginHostName}"
  HttpsURI:
    Value: !Sub "https://${OriginHostName}"
